Repository nikbulavin/cashsense, pull requests merged in 2024-10, with the labels that each got.

#33 Minor UI fixes
  app/build.gradle.kts
  feature/transaction/src/main/kotlin/ru/resodostudios/cashsense/feature/transaction/TransactionBottomSheet.kt
  feature/transaction/src/main/kotlin/ru/resodostudios/cashsense/feature/transaction/TransactionDialog.kt
  gradle/libs.versions.toml
Labels: enhancement

#32 Add filtering to CurrencyDropdownMenu
  core/locales/src/main/res/values-ru/strings.xml
  core/locales/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/ru/resodostudios/cashsense/core/ui/CurrencyDropdownMenu.kt
  feature/settings/src/main/kotlin/ru/resodostudios/cashsense/feature/settings/CurrencyDialog.kt
  feature/settings/src/main/kotlin/ru/resodostudios/cashsense/feature/settings/SettingsScreen.kt
  feature/subscription/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/subscription/dialog/SubscriptionDialog.kt
  feature/wallet/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/dialog/WalletDialog.kt
Labels: enhancement, hacktoberfest-accepted

#34 Rename app module to mobile
  baselineprofile/build.gradle.kts
  mobile/.gitignore
  mobile/build.gradle.kts
  mobile/google-services.json
  mobile/src/main/AndroidManifest.xml
  mobile/src/main/ic_launcher-playstore.png
  mobile/src/main/kotlin/ru/resodostudios/cashsense/CsApplication.kt
  mobile/src/main/kotlin/ru/resodostudios/cashsense/MainActivity.kt
  mobile/src/main/kotlin/ru/resodostudios/cashsense/MainActivityViewModel.kt
  mobile/src/main/kotlin/ru/resodostudios/cashsense/navigation/CsNavHost.kt
  mobile/src/main/kotlin/ru/resodostudios/cashsense/navigation/TopLevelDestination.kt
  mobile/src/main/kotlin/ru/resodostudios/cashsense/ui/CsApp.kt
  mobile/src/main/kotlin/ru/resodostudios/cashsense/ui/CsAppState.kt
  mobile/src/main/kotlin/ru/resodostudios/cashsense/ui/home2pane/Home2PaneViewModel.kt
  mobile/src/main/kotlin/ru/resodostudios/cashsense/ui/home2pane/HomeListDetailScreen.kt
  mobile/src/main/res/drawable/ic_launcher_background.xml
  mobile/src/main/res/drawable/ic_launcher_foreground.xml
  mobile/src/main/res/drawable/ic_launcher_monochrome.xml
  mobile/src/main/res/drawable/ic_splash.xml
  mobile/src/main/res/mipmap/ic_launcher.xml
  mobile/src/main/res/resources.properties
  mobile/src/main/res/values-night/themes.xml
  mobile/src/main/res/values/colors.xml
  mobile/src/main/res/values/strings.xml
  mobile/src/main/res/values/themes.xml
  mobile/src/main/res/xml/backup_rules.xml
  mobile/src/main/res/xml/data_extraction_rules.xml
  mobile/src/release/generated/baselineProfiles/baseline-prof.txt
  mobile/src/release/generated/baselineProfiles/startup-prof.txt
  settings.gradle.kts
Labels: enhancement

#35 Add filtering to CurrencyDropdownMenu & Fix finance amount animation
  core/locales/src/main/res/values-ru/strings.xml
  core/locales/src/main/res/values/strings.xml
  core/ui/src/main/kotlin/ru/resodostudios/cashsense/core/ui/CurrencyDropdownMenu.kt
  feature/settings/src/main/kotlin/ru/resodostudios/cashsense/feature/settings/CurrencyDialog.kt
  feature/settings/src/main/kotlin/ru/resodostudios/cashsense/feature/settings/SettingsScreen.kt
  feature/subscription/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/subscription/dialog/SubscriptionDialog.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletViewModel.kt
  feature/wallet/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/dialog/WalletDialog.kt
Labels: enhancement

#36 Improve documentation
  CODE_OF_CONDUCT.md
  README.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
Labels: documentation

#37 Update Kotlin to 2.0.21
  gradle/libs.versions.toml
Labels: enhancement

#38 Use jvmToolchain
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/JvmLibraryConventionPlugin.kt
  build-logic/convention/src/main/kotlin/ru/resodostudios/cashsense/KotlinAndroid.kt
Labels: enhancement

#39 Remove calculations of available months
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletScreen.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement
