Repository nikbulavin/cashsense, pull requests merged in 2025-01, with the labels that each got.

#68 Update Vico to 2.0.0-beta.6
  feature/category/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/category/dialog/CategoryDialogViewModel.kt
  feature/subscription/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/subscription/dialog/SubscriptionDialogViewModel.kt
  feature/transaction/src/main/kotlin/ru/resodostudios/cashsense/feature/transaction/TransactionDialogViewModel.kt
  feature/transfer/src/main/kotlin/ru/resodostudios/cashsense/feature/transfer/TransferDialogViewModel.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletScreen.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletViewModel.kt
  feature/wallet/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/dialog/WalletDialogViewModel.kt
  gradle/libs.versions.toml
  mobile/src/main/kotlin/ru/resodostudios/cashsense/ui/home2pane/Home2PaneViewModel.kt
Labels: dependencies

#69 Expand the boundaries of the month's selection
  core/ui/src/main/kotlin/ru/resodostudios/cashsense/core/ui/util/DateExtensions.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletScreen.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletViewModel.kt
  gradle/libs.versions.toml
Labels: enhancement

#70 Add previews for `HomeScreen`
  feature/home/src/main/kotlin/ru/resodostudios/cashsense/feature/home/ExtendedUserWalletPreviewParameterProvider.kt
  feature/home/src/main/kotlin/ru/resodostudios/cashsense/feature/home/HomeScreen.kt
  gradle/libs.versions.toml
Labels: enhancement

#71 Use line chart instead of columns for `FinanceGraph`
  core/ui/src/main/kotlin/ru/resodostudios/cashsense/core/ui/util/FormatExtensions.kt
  feature/home/src/main/kotlin/ru/resodostudios/cashsense/feature/home/HomeScreen.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/FinanceGraph.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletScreen.kt
  gradle/libs.versions.toml
Labels: enhancement

#73 Improve transactions filtering
  build-logic/convention/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidApplicationFirebaseConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidFeatureConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidLibraryComposeConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidRoomConventionPlugin.kt
  build-logic/convention/src/main/kotlin/AndroidTestConventionPlugin.kt
  build-logic/convention/src/main/kotlin/HiltConventionPlugin.kt
  build-logic/convention/src/main/kotlin/JvmLibraryConventionPlugin.kt
  core/data/src/main/kotlin/ru/resodostudios/cashsense/core/data/model/CurrencyExchangeRate.kt
  feature/home/src/main/kotlin/ru/resodostudios/cashsense/feature/home/HomeViewModel.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletScreen.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletViewModel.kt
  mobile/src/main/res/values/themes.xml
Labels: enhancement

#74 Add automatic removal of outdated exchange rates
  core/data/src/main/kotlin/ru/resodostudios/cashsense/core/data/repository/CurrencyConversionRepository.kt
  core/data/src/main/kotlin/ru/resodostudios/cashsense/core/data/repository/OfflineFirstCurrencyConversionRepository.kt
  core/database/src/main/kotlin/ru/resodostudios/cashsense/core/database/dao/CurrencyConversionDao.kt
  gradle/libs.versions.toml
  mobile/build.gradle.kts
  mobile/src/main/kotlin/ru/resodostudios/cashsense/CsApplication.kt
  settings.gradle.kts
  work/.gitignore
  work/build.gradle.kts
  work/src/main/kotlin/ru/resodostudios/cashsense/work/initializers/DeleteOutdatedRatesInitializer.kt
  work/src/main/kotlin/ru/resodostudios/cashsense/work/workers/DelegatingWorker.kt
  work/src/main/kotlin/ru/resodostudios/cashsense/work/workers/DeleteOutdatedRatesWorker.kt
Labels: enhancement

#77 Fix crash when input currency code is not 3-letter alphabetic code
  core/datastore/src/main/kotlin/ru/resodostudios/cashsense/core/datastore/CsPreferencesDataSource.kt
  core/datastore/src/main/kotlin/ru/resodostudios/cashsense/core/datastore/UserPreferencesSerializer.kt
Labels: bugfix

#78 Add haptic feedback on graph marker touch
  core/common/src/main/kotlin/ru/resodostudios/cashsense/core/util/Currency.kt
  core/datastore/src/main/kotlin/ru/resodostudios/cashsense/core/datastore/CsPreferencesDataSource.kt
  feature/subscription/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/subscription/dialog/SubscriptionDialog.kt
  feature/subscription/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/subscription/dialog/SubscriptionDialogEvent.kt
  feature/subscription/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/subscription/dialog/SubscriptionDialogViewModel.kt
  feature/transaction/src/main/kotlin/ru/resodostudios/cashsense/feature/transaction/TransactionDialog.kt
  feature/transaction/src/main/kotlin/ru/resodostudios/cashsense/feature/transaction/TransactionDialogEvent.kt
  feature/transaction/src/main/kotlin/ru/resodostudios/cashsense/feature/transaction/TransactionDialogViewModel.kt
  feature/transfer/src/main/kotlin/ru/resodostudios/cashsense/feature/transfer/TransferDialog.kt
  feature/transfer/src/main/kotlin/ru/resodostudios/cashsense/feature/transfer/TransferDialogViewModel.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/FinanceGraph.kt
  feature/wallet/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/dialog/WalletDialog.kt
  feature/wallet/dialog/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/dialog/WalletDialogViewModel.kt
Labels: enhancement

#79 Make `CategorySelectionRow` expandable
  core/ui/src/main/kotlin/ru/resodostudios/cashsense/core/ui/CategoryPreviewParameterProvider.kt
  feature/category/list/src/main/kotlin/ru/resodostudios/cashsense/feature/category/list/CategoriesScreen.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/TransactionList.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletScreen.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/component/CategorySelectionRow.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/component/FinanceGraph.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/component/TransactionBottomSheet.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/component/TransactionItem.kt
Labels: enhancement

#80 Fix crash in `CategorySelectionRow`
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletScreen.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletViewModel.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/component/CategorySelectionRow.kt
  gradle/libs.versions.toml
Labels: bugfix

#83 Fix calculation of finance progress
  core/ui/src/main/kotlin/ru/resodostudios/cashsense/core/ui/component/FinancePanel.kt
  feature/transaction/overview/src/main/kotlin/ru/resodostudios/cashsense/feature/transaction/overview/TransactionOverviewViewModel.kt
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletViewModel.kt
Labels: bugfix

#84 Update dependencies
  feature/wallet/detail/src/main/kotlin/ru/resodostudios/cashsense/feature/wallet/detail/WalletScreen.kt
  gradle.properties
  gradle/libs.versions.toml
Labels: dependencies
